services:
  web:
    image: koperasi
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      network: host
    volumes:
      - app_data:/var/www
    depends_on:
      - db
    env_file:
      - .env.docker
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["php-fpm"]
  queue:
    image: koperasi
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      network: host
    restart: always
    depends_on:
      - db
      - web
    command: php artisan queue:work
    env_file:
      - .env.docker
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - app_data:/var/www:ro
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
  db:
    image: mysql:8.1
    restart: always
    volumes:
      - .docker/db/data:/var/lib/mysql
      - .docker/logs:/var/log/mysql
      - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: koperasi
      MYSQL_USER: koperasi
      MYSQL_PASSWORD: koperasi
volumes:
  app_data: